services:
  vault-tls:
    image: hashicorp/vault:1.18.2
    container_name: vault
    restart: always
    ports:
      - 8201:8200
    volumes:
      - ./config/config.hcl:/vault/config/config.hcl
      - ./tls/tls-cert.pem:/vault/tls/cert.pem
      - ./tls/tls-ca.pem:/vault/tls/ca.pem
      - ./tls/tls-key.pem:/vault/tls/key.pem
      - ./volume/vault/data:/vault/data
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/config.hcl
    environment:
      - VAULT_ADDR=https://127.0.0.1:8200
      - VAULT_CACERT=/vault/tls/ca.pem
